#!/bin/bash


if ! [[ -d /scripts ]]
then
   sudo mkdir /scripts
fi


if [[ ! -e /scripts/upgrade ]]
then
	cat << EOF | sudo tee /scripts/upgrade > /dev/null
#!/bin/bash
sudo apt update
sudo apt -y upgrade
sudo apt -y full-upgrade
sudo apt -y autoremove
sudo apt -y clean
sudo apt -y purge
EOF
	sudo chmod +x /scripts/upgrade	
	echo "/scripts/upgrade done!"
fi

sudo apt -y install htop screen mc

sudo sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
if ! $(sudo grep -q afowler /root/.zshrc)
then
    sudo sed -i '${s/$ZSH_THEME=.*/$ZSH_THEME=\"afowler\"/}' /root/.zshrc
    cat << EOF | sudo tee /root/.zshrc > /dev/null
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

export PATH=$PATH:/scripts/
EOF
	echo " /root/.zshrc modified!"
fi


sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
if ! $(grep -q afowler ~/.zshrc)
then
    sed -i '${s/ZSH_THEME=.*/ZSH_THEME=\"afowler\"/}' ~/.zshrc
    cat << EOF >>  ~/.zshrc 
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

export PATH=$PATH:/scripts/
EOF
	echo " ~/.zshrc modified!"
fi




